
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.common
{
/// <summary>
/// 游戏基础规则表
/// </summary>
public partial class TbGameRule
{
    private readonly System.Collections.Generic.Dictionary<string, common.GameRule> _dataMap;
    private readonly System.Collections.Generic.List<common.GameRule> _dataList;
    
    public TbGameRule(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, common.GameRule>(n);
        _dataList = new System.Collections.Generic.List<common.GameRule>(n);
        for(int i = n ; i > 0 ; --i)
        {
            common.GameRule _v;
            _v = global::GameConfig.common.GameRule.DeserializeGameRule(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, common.GameRule> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<common.GameRule> DataList => _dataList;

    public common.GameRule GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public common.GameRule Get(string key) => _dataMap[key];
    public common.GameRule this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

