
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.asset
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        ItemType = _buf.ReadString();
        Name = _buf.ReadString();
        Quality = _buf.ReadInt();
        MaxStack = _buf.ReadInt();
        UseType = _buf.ReadString();
        EffectType = _buf.ReadString();
        EffectParam = _buf.ReadString();
        IconAsset = _buf.ReadString();
        Description = _buf.ReadString();
    }

    public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new asset.ItemConfig(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 道具类型：Ticket/Consumable/Fragment/Chest/Trial/Material
    /// </summary>
    public readonly string ItemType;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 堆叠上限
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 使用方式：None/UseDirectly/OpenChest/ActivateBuff/Exchange
    /// </summary>
    public readonly string UseType;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly string EffectType;
    /// <summary>
    /// 效果参数
    /// </summary>
    public readonly string EffectParam;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string IconAsset;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = 1983244819;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "itemType:" + ItemType + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "maxStack:" + MaxStack + ","
        + "useType:" + UseType + ","
        + "effectType:" + EffectType + ","
        + "effectParam:" + EffectParam + ","
        + "iconAsset:" + IconAsset + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

