
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.asset
{
/// <summary>
/// 局外货币配置表：金币、钻石、活动币等纯数值资产
/// </summary>
public partial class TbCurrency
{
    private readonly System.Collections.Generic.Dictionary<int, asset.CurrencyConfig> _dataMap;
    private readonly System.Collections.Generic.List<asset.CurrencyConfig> _dataList;
    
    public TbCurrency(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, asset.CurrencyConfig>(n);
        _dataList = new System.Collections.Generic.List<asset.CurrencyConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            asset.CurrencyConfig _v;
            _v = global::GameConfig.asset.CurrencyConfig.DeserializeCurrencyConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CurrencyId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, asset.CurrencyConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<asset.CurrencyConfig> DataList => _dataList;

    public asset.CurrencyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public asset.CurrencyConfig Get(int key) => _dataMap[key];
    public asset.CurrencyConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

