
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.open
{
public sealed partial class OpenFeatureConfig : Luban.BeanBase
{
    public OpenFeatureConfig(ByteBuf _buf) 
    {
        FeatureId = _buf.ReadString();
        Name = _buf.ReadString();
        Category = _buf.ReadString();
        OpenConditionType = _buf.ReadString();
        OpenParam = _buf.ReadString();
        StartTime = _buf.ReadString();
        EndTime = _buf.ReadString();
        IsEnabled = _buf.ReadBool();
        Comment = _buf.ReadString();
    }

    public static OpenFeatureConfig DeserializeOpenFeatureConfig(ByteBuf _buf)
    {
        return new open.OpenFeatureConfig(_buf);
    }

    /// <summary>
    /// 开放ID；其他表通过该字段关联
    /// </summary>
    public readonly string FeatureId;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 分类：Daily/Shop/Activity/System
    /// </summary>
    public readonly string Category;
    /// <summary>
    /// Always/TimeRange/Level/ServerSwitch
    /// </summary>
    public readonly string OpenConditionType;
    /// <summary>
    /// 开放参数，按类型解释
    /// </summary>
    public readonly string OpenParam;
    /// <summary>
    /// UTC开始时间，空表示不限
    /// </summary>
    public readonly string StartTime;
    /// <summary>
    /// UTC结束时间，空表示不限
    /// </summary>
    public readonly string EndTime;
    /// <summary>
    /// 总开关
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = -1171835670;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "featureId:" + FeatureId + ","
        + "name:" + Name + ","
        + "category:" + Category + ","
        + "openConditionType:" + OpenConditionType + ","
        + "openParam:" + OpenParam + ","
        + "startTime:" + StartTime + ","
        + "endTime:" + EndTime + ","
        + "isEnabled:" + IsEnabled + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

