
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.open
{
/// <summary>
/// 统一开放定义表：活动、功能、限时入口、任务和商店共用
/// </summary>
public partial class TbOpenFeature
{
    private readonly System.Collections.Generic.Dictionary<string, open.OpenFeatureConfig> _dataMap;
    private readonly System.Collections.Generic.List<open.OpenFeatureConfig> _dataList;
    
    public TbOpenFeature(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, open.OpenFeatureConfig>(n);
        _dataList = new System.Collections.Generic.List<open.OpenFeatureConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            open.OpenFeatureConfig _v;
            _v = global::GameConfig.open.OpenFeatureConfig.DeserializeOpenFeatureConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FeatureId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, open.OpenFeatureConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<open.OpenFeatureConfig> DataList => _dataList;

    public open.OpenFeatureConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public open.OpenFeatureConfig Get(string key) => _dataMap[key];
    public open.OpenFeatureConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

