
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// 游戏基础规则表
    /// </summary>
    public common.TbGameRule TbGameRule {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbGameRule = new common.TbGameRule(loader("common_tbgamerule"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGameRule.ResolveRef(this);
    }
}

}
