
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.role
{
public sealed partial class CharacterConfig : Luban.BeanBase
{
    public CharacterConfig(ByteBuf _buf) 
    {
        CharacterId = _buf.ReadInt();
        Category = _buf.ReadString();
        Race = _buf.ReadString();
        Name = _buf.ReadString();
        AbilityId = _buf.ReadInt();
        AbilityName = _buf.ReadString();
        AbilityDesc = _buf.ReadString();
        IconAsset = _buf.ReadString();
        PrefabAsset = _buf.ReadString();
        IsInitial = _buf.ReadBool();
        SortOrder = _buf.ReadInt();
        Description = _buf.ReadString();
    }

    public static CharacterConfig DeserializeCharacterConfig(ByteBuf _buf)
    {
        return new role.CharacterConfig(_buf);
    }

    /// <summary>
    /// 角色ID
    /// </summary>
    public readonly int CharacterId;
    /// <summary>
    /// 角色分类：Hero/Ghost
    /// </summary>
    public readonly string Category;
    /// <summary>
    /// 种族/阵营：Elf/Troll
    /// </summary>
    public readonly string Race;
    /// <summary>
    /// 角色名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int AbilityId;
    /// <summary>
    /// 技能名称
    /// </summary>
    public readonly string AbilityName;
    /// <summary>
    /// 技能描述
    /// </summary>
    public readonly string AbilityDesc;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string IconAsset;
    /// <summary>
    /// 预制体资源名
    /// </summary>
    public readonly string PrefabAsset;
    /// <summary>
    /// 是否初始解锁
    /// </summary>
    public readonly bool IsInitial;
    /// <summary>
    /// 排序权重
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 角色说明
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -1005465037;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "characterId:" + CharacterId + ","
        + "category:" + Category + ","
        + "race:" + Race + ","
        + "name:" + Name + ","
        + "abilityId:" + AbilityId + ","
        + "abilityName:" + AbilityName + ","
        + "abilityDesc:" + AbilityDesc + ","
        + "iconAsset:" + IconAsset + ","
        + "prefabAsset:" + PrefabAsset + ","
        + "isInitial:" + IsInitial + ","
        + "sortOrder:" + SortOrder + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

