
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.role
{
/// <summary>
/// 角色配置表：精灵/巨魔角色、技能、资源和解锁状态
/// </summary>
public partial class TbCharacter
{
    private readonly System.Collections.Generic.Dictionary<int, role.CharacterConfig> _dataMap;
    private readonly System.Collections.Generic.List<role.CharacterConfig> _dataList;
    
    public TbCharacter(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, role.CharacterConfig>(n);
        _dataList = new System.Collections.Generic.List<role.CharacterConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            role.CharacterConfig _v;
            _v = global::GameConfig.role.CharacterConfig.DeserializeCharacterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CharacterId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, role.CharacterConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<role.CharacterConfig> DataList => _dataList;

    public role.CharacterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public role.CharacterConfig Get(int key) => _dataMap[key];
    public role.CharacterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

