
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.asset
{
public sealed partial class CurrencyConfig : Luban.BeanBase
{
    public CurrencyConfig(ByteBuf _buf) 
    {
        CurrencyId = _buf.ReadInt();
        Code = _buf.ReadString();
        Name = _buf.ReadString();
        IconAsset = _buf.ReadString();
        IsPremium = _buf.ReadBool();
        SortOrder = _buf.ReadInt();
        Description = _buf.ReadString();
    }

    public static CurrencyConfig DeserializeCurrencyConfig(ByteBuf _buf)
    {
        return new asset.CurrencyConfig(_buf);
    }

    /// <summary>
    /// 货币ID
    /// </summary>
    public readonly int CurrencyId;
    /// <summary>
    /// 货币代码
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string IconAsset;
    /// <summary>
    /// 是否付费货币
    /// </summary>
    public readonly bool IsPremium;
    /// <summary>
    /// 排序权重
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = 968624529;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "currencyId:" + CurrencyId + ","
        + "code:" + Code + ","
        + "name:" + Name + ","
        + "iconAsset:" + IconAsset + ","
        + "isPremium:" + IsPremium + ","
        + "sortOrder:" + SortOrder + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

