
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.asset
{
/// <summary>
/// 局外道具配置表：票券、体验卡、碎片、增益卡、宝箱和材料
/// </summary>
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<int, asset.ItemConfig> _dataMap;
    private readonly System.Collections.Generic.List<asset.ItemConfig> _dataList;
    
    public TbItem(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, asset.ItemConfig>(n);
        _dataList = new System.Collections.Generic.List<asset.ItemConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            asset.ItemConfig _v;
            _v = global::GameConfig.asset.ItemConfig.DeserializeItemConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, asset.ItemConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<asset.ItemConfig> DataList => _dataList;

    public asset.ItemConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public asset.ItemConfig Get(int key) => _dataMap[key];
    public asset.ItemConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

