
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class BattleShopConfig : Luban.BeanBase
{
    public BattleShopConfig(ByteBuf _buf) 
    {
        ShopId = _buf.ReadInt();
        ShopName = _buf.ReadString();
        ShopType = _buf.ReadString();
        GoodsGroupId = _buf.ReadInt();
        OwnerCamp = _buf.ReadString();
        Comment = _buf.ReadString();
        EffectDesc = _buf.ReadString();
    }

    public static BattleShopConfig DeserializeBattleShopConfig(ByteBuf _buf)
    {
        return new battle.BattleShopConfig(_buf);
    }

    /// <summary>
    /// 商店ID
    /// </summary>
    public readonly int ShopId;
    /// <summary>
    /// 商店显示名
    /// </summary>
    public readonly string ShopName;
    /// <summary>
    /// 商店类型，例如 TrollWeapon
    /// </summary>
    public readonly string ShopType;
    /// <summary>
    /// 商品组ID；关联 battle_shop_goods.goodsGroupId
    /// </summary>
    public readonly int GoodsGroupId;
    /// <summary>
    /// 可使用阵营，例如 Troll
    /// </summary>
    public readonly string OwnerCamp;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 效果说明
    /// </summary>
    public readonly string EffectDesc;
   
    public const int __ID__ = -1901543610;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "shopId:" + ShopId + ","
        + "shopName:" + ShopName + ","
        + "shopType:" + ShopType + ","
        + "goodsGroupId:" + GoodsGroupId + ","
        + "ownerCamp:" + OwnerCamp + ","
        + "comment:" + Comment + ","
        + "effectDesc:" + EffectDesc + ","
        + "}";
    }
}
}

