
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class BuildingCardConfig : Luban.BeanBase
{
    public BuildingCardConfig(ByteBuf _buf) 
    {
        CardId = _buf.ReadInt();
        BuildingId = _buf.ReadInt();
        CardName = _buf.ReadString();
        IconAsset = _buf.ReadString();
        SortOrder = _buf.ReadInt();
        UnlockRule = _buf.ReadString();
        CostGold = _buf.ReadInt();
        CostWood = _buf.ReadInt();
        CooldownMs = _buf.ReadInt();
        Description = _buf.ReadString();
        EffectDesc = _buf.ReadString();
    }

    public static BuildingCardConfig DeserializeBuildingCardConfig(ByteBuf _buf)
    {
        return new battle.BuildingCardConfig(_buf);
    }

    /// <summary>
    /// 卡牌ID
    /// </summary>
    public readonly int CardId;
    /// <summary>
    /// 建筑ID；关联 building.buildingId
    /// </summary>
    public readonly int BuildingId;
    /// <summary>
    /// 卡牌显示名
    /// </summary>
    public readonly string CardName;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string IconAsset;
    /// <summary>
    /// 排序权重
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 解锁规则，空表示默认解锁
    /// </summary>
    public readonly string UnlockRule;
    /// <summary>
    /// 金币消耗
    /// </summary>
    public readonly int CostGold;
    /// <summary>
    /// 木材消耗
    /// </summary>
    public readonly int CostWood;
    /// <summary>
    /// 建造冷却毫秒
    /// </summary>
    public readonly int CooldownMs;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 效果说明
    /// </summary>
    public readonly string EffectDesc;
   
    public const int __ID__ = 293768540;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "cardId:" + CardId + ","
        + "buildingId:" + BuildingId + ","
        + "cardName:" + CardName + ","
        + "iconAsset:" + IconAsset + ","
        + "sortOrder:" + SortOrder + ","
        + "unlockRule:" + UnlockRule + ","
        + "costGold:" + CostGold + ","
        + "costWood:" + CostWood + ","
        + "cooldownMs:" + CooldownMs + ","
        + "description:" + Description + ","
        + "effectDesc:" + EffectDesc + ","
        + "}";
    }
}
}

