
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 建筑卡牌表：局内建造入口、消耗、冷却和展示说明
/// </summary>
public partial class TbBuildingLevel
{
    private readonly System.Collections.Generic.Dictionary<int, battle.BuildingLevelConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.BuildingLevelConfig> _dataList;
    
    public TbBuildingLevel(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.BuildingLevelConfig>(n);
        _dataList = new System.Collections.Generic.List<battle.BuildingLevelConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.BuildingLevelConfig _v;
            _v = global::GameConfig.battle.BuildingLevelConfig.DeserializeBuildingLevelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.LevelId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.BuildingLevelConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.BuildingLevelConfig> DataList => _dataList;

    public battle.BuildingLevelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.BuildingLevelConfig Get(int key) => _dataMap[key];
    public battle.BuildingLevelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

