
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 怪物配置表：Tiled monster 层对象通过 monster_id 引用
/// </summary>
public partial class TbMonster
{
    private readonly System.Collections.Generic.Dictionary<int, battle.MonsterConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.MonsterConfig> _dataList;
    
    public TbMonster(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.MonsterConfig>(n);
        _dataList = new System.Collections.Generic.List<battle.MonsterConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.MonsterConfig _v;
            _v = global::GameConfig.battle.MonsterConfig.DeserializeMonsterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.MonsterId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.MonsterConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.MonsterConfig> DataList => _dataList;

    public battle.MonsterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.MonsterConfig Get(int key) => _dataMap[key];
    public battle.MonsterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

