
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 局内商店表：Tiled shop 层对象通过 shop_id 引用
/// </summary>
public partial class TbShop
{
    private readonly System.Collections.Generic.Dictionary<int, battle.ShopConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.ShopConfig> _dataList;
    
    public TbShop(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.ShopConfig>(n);
        _dataList = new System.Collections.Generic.List<battle.ShopConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.ShopConfig _v;
            _v = global::GameConfig.battle.ShopConfig.DeserializeShopConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ShopId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.ShopConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.ShopConfig> DataList => _dataList;

    public battle.ShopConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.ShopConfig Get(int key) => _dataMap[key];
    public battle.ShopConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

