
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.shop
{
public sealed partial class ShopConfig : Luban.BeanBase
{
    public ShopConfig(ByteBuf _buf) 
    {
        ShopId = _buf.ReadInt();
        ShopName = _buf.ReadString();
        ShopType = _buf.ReadString();
        FeatureId = _buf.ReadString();
        ActivityId = _buf.ReadString();
        GoodsGroupId = _buf.ReadInt();
        RefreshGroup = _buf.ReadString();
        Comment = _buf.ReadString();
    }

    public static ShopConfig DeserializeShopConfig(ByteBuf _buf)
    {
        return new shop.ShopConfig(_buf);
    }

    /// <summary>
    /// 商店ID
    /// </summary>
    public readonly int ShopId;
    /// <summary>
    /// 商店显示名
    /// </summary>
    public readonly string ShopName;
    /// <summary>
    /// 商店类型：Normal/Activity/Limited
    /// </summary>
    public readonly string ShopType;
    /// <summary>
    /// 关联 open_feature.featureId
    /// </summary>
    public readonly string FeatureId;
    /// <summary>
    /// 活动ID，仅用于归类筛选
    /// </summary>
    public readonly string ActivityId;
    /// <summary>
    /// 商品组ID；关联 shop_goods.goodsGroupId
    /// </summary>
    public readonly int GoodsGroupId;
    /// <summary>
    /// 刷新组：Daily/Weekly/Activity.xxx/Permanent
    /// </summary>
    public readonly string RefreshGroup;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = -1058503696;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "shopId:" + ShopId + ","
        + "shopName:" + ShopName + ","
        + "shopType:" + ShopType + ","
        + "featureId:" + FeatureId + ","
        + "activityId:" + ActivityId + ","
        + "goodsGroupId:" + GoodsGroupId + ","
        + "refreshGroup:" + RefreshGroup + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

