
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.shop
{
public sealed partial class ShopGoodsConfig : Luban.BeanBase
{
    public ShopGoodsConfig(ByteBuf _buf) 
    {
        GoodsId = _buf.ReadInt();
        GoodsGroupId = _buf.ReadInt();
        ItemId = _buf.ReadInt();
        ItemName = _buf.ReadString();
        Price = _buf.ReadInt();
        Currency = _buf.ReadString();
        BuyLimit = _buf.ReadInt();
        RewardItemCount = _buf.ReadInt();
        UnlockRule = _buf.ReadString();
        Comment = _buf.ReadString();
        EffectDesc = _buf.ReadString();
    }

    public static ShopGoodsConfig DeserializeShopGoodsConfig(ByteBuf _buf)
    {
        return new shop.ShopGoodsConfig(_buf);
    }

    /// <summary>
    /// 商品ID
    /// </summary>
    public readonly int GoodsId;
    /// <summary>
    /// 商品组ID；关联 shop.goodsGroupId
    /// </summary>
    public readonly int GoodsGroupId;
    /// <summary>
    /// 奖励道具ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 商品显示名
    /// </summary>
    public readonly string ItemName;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 货币类型：Gold/Diamond/EventToken
    /// </summary>
    public readonly string Currency;
    /// <summary>
    /// 购买上限，0表示不限
    /// </summary>
    public readonly int BuyLimit;
    /// <summary>
    /// 每次购买获得数量
    /// </summary>
    public readonly int RewardItemCount;
    /// <summary>
    /// 解锁条件，空表示默认解锁
    /// </summary>
    public readonly string UnlockRule;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 效果说明
    /// </summary>
    public readonly string EffectDesc;
   
    public const int __ID__ = -1502549430;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "goodsId:" + GoodsId + ","
        + "goodsGroupId:" + GoodsGroupId + ","
        + "itemId:" + ItemId + ","
        + "itemName:" + ItemName + ","
        + "price:" + Price + ","
        + "currency:" + Currency + ","
        + "buyLimit:" + BuyLimit + ","
        + "rewardItemCount:" + RewardItemCount + ","
        + "unlockRule:" + UnlockRule + ","
        + "comment:" + Comment + ","
        + "effectDesc:" + EffectDesc + ","
        + "}";
    }
}
}

