
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.shop
{
/// <summary>
/// 局外商店商品表
/// </summary>
public partial class TbShopGoods
{
    private readonly System.Collections.Generic.Dictionary<int, shop.ShopGoodsConfig> _dataMap;
    private readonly System.Collections.Generic.List<shop.ShopGoodsConfig> _dataList;
    
    public TbShopGoods(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, shop.ShopGoodsConfig>(n);
        _dataList = new System.Collections.Generic.List<shop.ShopGoodsConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            shop.ShopGoodsConfig _v;
            _v = global::GameConfig.shop.ShopGoodsConfig.DeserializeShopGoodsConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GoodsId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, shop.ShopGoodsConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<shop.ShopGoodsConfig> DataList => _dataList;

    public shop.ShopGoodsConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public shop.ShopGoodsConfig Get(int key) => _dataMap[key];
    public shop.ShopGoodsConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

