
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.common
{
public sealed partial class GameRule : Luban.BeanBase
{
    public GameRule(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Module = _buf.ReadString();
        Key = _buf.ReadString();
        IntValue = _buf.ReadInt();
        StringValue = _buf.ReadString();
        BoolValue = _buf.ReadBool();
        Comment = _buf.ReadString();
        EffectDesc = _buf.ReadString();
    }

    public static GameRule DeserializeGameRule(ByteBuf _buf)
    {
        return new common.GameRule(_buf);
    }

    /// <summary>
    /// 规则ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属模块
    /// </summary>
    public readonly string Module;
    /// <summary>
    /// 规则键
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 整数值
    /// </summary>
    public readonly int IntValue;
    /// <summary>
    /// 字符串值
    /// </summary>
    public readonly string StringValue;
    /// <summary>
    /// 布尔值
    /// </summary>
    public readonly bool BoolValue;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 效果说明
    /// </summary>
    public readonly string EffectDesc;
   
    public const int __ID__ = 1222390481;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "module:" + Module + ","
        + "key:" + Key + ","
        + "intValue:" + IntValue + ","
        + "stringValue:" + StringValue + ","
        + "boolValue:" + BoolValue + ","
        + "comment:" + Comment + ","
        + "effectDesc:" + EffectDesc + ","
        + "}";
    }
}
}

