
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class BuildingConfig : Luban.BeanBase
{
    public BuildingConfig(ByteBuf _buf) 
    {
        BuildingId = _buf.ReadInt();
        BuildingName = _buf.ReadString();
        BuildingType = _buf.ReadString();
        PrefabAsset = _buf.ReadString();
        FootprintWidth = _buf.ReadInt();
        FootprintHeight = _buf.ReadInt();
        MaxLevel = _buf.ReadInt();
        BaseHp = _buf.ReadInt();
        PowerCost = _buf.ReadInt();
        RecyclePercent = _buf.ReadInt();
        CanUpgrade = _buf.ReadBool();
        CanRepair = _buf.ReadBool();
        CanBlockPath = _buf.ReadBool();
        Comment = _buf.ReadString();
        EffectDesc = _buf.ReadString();
    }

    public static BuildingConfig DeserializeBuildingConfig(ByteBuf _buf)
    {
        return new battle.BuildingConfig(_buf);
    }

    /// <summary>
    /// 建筑ID
    /// </summary>
    public readonly int BuildingId;
    /// <summary>
    /// 建筑显示名
    /// </summary>
    public readonly string BuildingName;
    /// <summary>
    /// 建筑类型：Wall/Tower/Support/Core
    /// </summary>
    public readonly string BuildingType;
    /// <summary>
    /// 建筑预制体资源名；后续放在 AssetRaw/Actor/Battle
    /// </summary>
    public readonly string PrefabAsset;
    /// <summary>
    /// 占地宽度
    /// </summary>
    public readonly int FootprintWidth;
    /// <summary>
    /// 占地高度
    /// </summary>
    public readonly int FootprintHeight;
    /// <summary>
    /// 最高等级
    /// </summary>
    public readonly int MaxLevel;
    /// <summary>
    /// 基础生命值
    /// </summary>
    public readonly int BaseHp;
    /// <summary>
    /// 电力消耗
    /// </summary>
    public readonly int PowerCost;
    /// <summary>
    /// 回收返还比例
    /// </summary>
    public readonly int RecyclePercent;
    /// <summary>
    /// 是否可升级
    /// </summary>
    public readonly bool CanUpgrade;
    /// <summary>
    /// 是否可维修
    /// </summary>
    public readonly bool CanRepair;
    /// <summary>
    /// 是否阻挡路径
    /// </summary>
    public readonly bool CanBlockPath;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 效果说明
    /// </summary>
    public readonly string EffectDesc;
   
    public const int __ID__ = -603736276;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "buildingId:" + BuildingId + ","
        + "buildingName:" + BuildingName + ","
        + "buildingType:" + BuildingType + ","
        + "prefabAsset:" + PrefabAsset + ","
        + "footprintWidth:" + FootprintWidth + ","
        + "footprintHeight:" + FootprintHeight + ","
        + "maxLevel:" + MaxLevel + ","
        + "baseHp:" + BaseHp + ","
        + "powerCost:" + PowerCost + ","
        + "recyclePercent:" + RecyclePercent + ","
        + "canUpgrade:" + CanUpgrade + ","
        + "canRepair:" + CanRepair + ","
        + "canBlockPath:" + CanBlockPath + ","
        + "comment:" + Comment + ","
        + "effectDesc:" + EffectDesc + ","
        + "}";
    }
}
}

