
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class BuildingLevelConfig : Luban.BeanBase
{
    public BuildingLevelConfig(ByteBuf _buf) 
    {
        LevelId = _buf.ReadInt();
        BuildingId = _buf.ReadInt();
        Level = _buf.ReadInt();
        UpgradeCostGold = _buf.ReadInt();
        UpgradeCostWood = _buf.ReadInt();
        UpgradeTimeMs = _buf.ReadInt();
        Hp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        AttackRange = _buf.ReadInt();
        AttackIntervalMs = _buf.ReadInt();
        RepairValue = _buf.ReadInt();
        NextLevelId = _buf.ReadInt();
        Comment = _buf.ReadString();
        EffectDesc = _buf.ReadString();
    }

    public static BuildingLevelConfig DeserializeBuildingLevelConfig(ByteBuf _buf)
    {
        return new battle.BuildingLevelConfig(_buf);
    }

    /// <summary>
    /// 建筑等级ID
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 建筑ID；关联 building.buildingId
    /// </summary>
    public readonly int BuildingId;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 升级金币消耗
    /// </summary>
    public readonly int UpgradeCostGold;
    /// <summary>
    /// 升级木材消耗
    /// </summary>
    public readonly int UpgradeCostWood;
    /// <summary>
    /// 升级耗时毫秒
    /// </summary>
    public readonly int UpgradeTimeMs;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 攻击范围
    /// </summary>
    public readonly int AttackRange;
    /// <summary>
    /// 攻击/产出间隔毫秒
    /// </summary>
    public readonly int AttackIntervalMs;
    /// <summary>
    /// 维修值/产出值
    /// </summary>
    public readonly int RepairValue;
    /// <summary>
    /// 下一等级ID；0 表示满级
    /// </summary>
    public readonly int NextLevelId;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 效果说明
    /// </summary>
    public readonly string EffectDesc;
   
    public const int __ID__ = 315491900;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "levelId:" + LevelId + ","
        + "buildingId:" + BuildingId + ","
        + "level:" + Level + ","
        + "upgradeCostGold:" + UpgradeCostGold + ","
        + "upgradeCostWood:" + UpgradeCostWood + ","
        + "upgradeTimeMs:" + UpgradeTimeMs + ","
        + "hp:" + Hp + ","
        + "attack:" + Attack + ","
        + "attackRange:" + AttackRange + ","
        + "attackIntervalMs:" + AttackIntervalMs + ","
        + "repairValue:" + RepairValue + ","
        + "nextLevelId:" + NextLevelId + ","
        + "comment:" + Comment + ","
        + "effectDesc:" + EffectDesc + ","
        + "}";
    }
}
}

