
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class MapConfig : Luban.BeanBase
{
    public MapConfig(ByteBuf _buf) 
    {
        MapId = _buf.ReadInt();
        MapName = _buf.ReadString();
        MapAsset = _buf.ReadString();
        Mode = _buf.ReadString();
        MinPlayers = _buf.ReadInt();
        MaxPlayers = _buf.ReadInt();
        RecommendedPlayers = _buf.ReadInt();
        TiledObjectLayers = _buf.ReadString();
        Comment = _buf.ReadString();
        EffectDesc = _buf.ReadString();
    }

    public static MapConfig DeserializeMapConfig(ByteBuf _buf)
    {
        return new battle.MapConfig(_buf);
    }

    /// <summary>
    /// 地图ID
    /// </summary>
    public readonly int MapId;
    /// <summary>
    /// 地图显示名
    /// </summary>
    public readonly string MapName;
    /// <summary>
    /// Tiled 导出的地图资源地址，不带扩展名；与 AssetRaw/Maps 下 JSON 文件名一致
    /// </summary>
    public readonly string MapAsset;
    /// <summary>
    /// 默认玩法模式
    /// </summary>
    public readonly string Mode;
    /// <summary>
    /// 允许进入该地图的最少玩家数
    /// </summary>
    public readonly int MinPlayers;
    /// <summary>
    /// 允许进入该地图的最多玩家数
    /// </summary>
    public readonly int MaxPlayers;
    /// <summary>
    /// 推荐玩家数，用于 UI 展示和房间默认人数
    /// </summary>
    public readonly int RecommendedPlayers;
    /// <summary>
    /// Tiled 对象层约定，逗号分隔，例如 spawn,shop,monster
    /// </summary>
    public readonly string TiledObjectLayers;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 效果说明
    /// </summary>
    public readonly string EffectDesc;
   
    public const int __ID__ = 1182588392;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "mapId:" + MapId + ","
        + "mapName:" + MapName + ","
        + "mapAsset:" + MapAsset + ","
        + "mode:" + Mode + ","
        + "minPlayers:" + MinPlayers + ","
        + "maxPlayers:" + MaxPlayers + ","
        + "recommendedPlayers:" + RecommendedPlayers + ","
        + "tiledObjectLayers:" + TiledObjectLayers + ","
        + "comment:" + Comment + ","
        + "effectDesc:" + EffectDesc + ","
        + "}";
    }
}
}

