
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class MonsterConfig : Luban.BeanBase
{
    public MonsterConfig(ByteBuf _buf) 
    {
        MonsterId = _buf.ReadInt();
        MonsterName = _buf.ReadString();
        PrefabAsset = _buf.ReadString();
        Hp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        MoveSpeed = _buf.ReadFloat();
        AiType = _buf.ReadString();
        Comment = _buf.ReadString();
        EffectDesc = _buf.ReadString();
    }

    public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
    {
        return new battle.MonsterConfig(_buf);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public readonly int MonsterId;
    /// <summary>
    /// 怪物显示名
    /// </summary>
    public readonly string MonsterName;
    /// <summary>
    /// 怪物预制体资源地址；后续放在 AssetRaw/Actor/Battle
    /// </summary>
    public readonly string PrefabAsset;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// AI 类型，例如 Patrol/Guard/Chase
    /// </summary>
    public readonly string AiType;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 效果说明
    /// </summary>
    public readonly string EffectDesc;
   
    public const int __ID__ = 1749091558;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "monsterId:" + MonsterId + ","
        + "monsterName:" + MonsterName + ","
        + "prefabAsset:" + PrefabAsset + ","
        + "hp:" + Hp + ","
        + "attack:" + Attack + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "aiType:" + AiType + ","
        + "comment:" + Comment + ","
        + "effectDesc:" + EffectDesc + ","
        + "}";
    }
}
}

