
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class ShopGoodsConfig : Luban.BeanBase
{
    public ShopGoodsConfig(ByteBuf _buf) 
    {
        GoodsId = _buf.ReadInt();
        GoodsGroupId = _buf.ReadInt();
        ItemId = _buf.ReadInt();
        ItemName = _buf.ReadString();
        Price = _buf.ReadInt();
        Currency = _buf.ReadString();
        UnlockRule = _buf.ReadString();
        Comment = _buf.ReadString();
        EffectDesc = _buf.ReadString();
    }

    public static ShopGoodsConfig DeserializeShopGoodsConfig(ByteBuf _buf)
    {
        return new battle.ShopGoodsConfig(_buf);
    }

    /// <summary>
    /// 商品ID
    /// </summary>
    public readonly int GoodsId;
    /// <summary>
    /// 商品组ID；关联 shop.goodsGroupId
    /// </summary>
    public readonly int GoodsGroupId;
    /// <summary>
    /// 物品ID；后续关联 item/weapon 表
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 商品显示名
    /// </summary>
    public readonly string ItemName;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 货币类型，例如 Gold
    /// </summary>
    public readonly string Currency;
    /// <summary>
    /// 解锁条件，空表示默认解锁
    /// </summary>
    public readonly string UnlockRule;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 效果说明
    /// </summary>
    public readonly string EffectDesc;
   
    public const int __ID__ = -1305240564;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "goodsId:" + GoodsId + ","
        + "goodsGroupId:" + GoodsGroupId + ","
        + "itemId:" + ItemId + ","
        + "itemName:" + ItemName + ","
        + "price:" + Price + ","
        + "currency:" + Currency + ","
        + "unlockRule:" + UnlockRule + ","
        + "comment:" + Comment + ","
        + "effectDesc:" + EffectDesc + ","
        + "}";
    }
}
}

