
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 局内商店表：Tiled shop 层对象通过 shop_id 引用
/// </summary>
public partial class TbBattleShop
{
    private readonly System.Collections.Generic.Dictionary<int, battle.BattleShopConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.BattleShopConfig> _dataList;
    
    public TbBattleShop(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.BattleShopConfig>(n);
        _dataList = new System.Collections.Generic.List<battle.BattleShopConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.BattleShopConfig _v;
            _v = global::GameConfig.battle.BattleShopConfig.DeserializeBattleShopConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ShopId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.BattleShopConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.BattleShopConfig> DataList => _dataList;

    public battle.BattleShopConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.BattleShopConfig Get(int key) => _dataMap[key];
    public battle.BattleShopConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

