
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 局内商店商品表：定义本局售卖物品、价格和解锁条件
/// </summary>
public partial class TbBattleShopGoods
{
    private readonly System.Collections.Generic.Dictionary<int, battle.BattleShopGoodsConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.BattleShopGoodsConfig> _dataList;
    
    public TbBattleShopGoods(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.BattleShopGoodsConfig>(n);
        _dataList = new System.Collections.Generic.List<battle.BattleShopGoodsConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.BattleShopGoodsConfig _v;
            _v = global::GameConfig.battle.BattleShopGoodsConfig.DeserializeBattleShopGoodsConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GoodsId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.BattleShopGoodsConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.BattleShopGoodsConfig> DataList => _dataList;

    public battle.BattleShopGoodsConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.BattleShopGoodsConfig Get(int key) => _dataMap[key];
    public battle.BattleShopGoodsConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

