
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 建筑配置表：建筑类型、预制体、占地、生命值和能力开关
/// </summary>
public partial class TbBuilding
{
    private readonly System.Collections.Generic.Dictionary<int, battle.BuildingConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.BuildingConfig> _dataList;
    
    public TbBuilding(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.BuildingConfig>(n);
        _dataList = new System.Collections.Generic.List<battle.BuildingConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.BuildingConfig _v;
            _v = global::GameConfig.battle.BuildingConfig.DeserializeBuildingConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BuildingId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.BuildingConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.BuildingConfig> DataList => _dataList;

    public battle.BuildingConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.BuildingConfig Get(int key) => _dataMap[key];
    public battle.BuildingConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

