
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 建筑等级表：升级消耗、生命值、攻击、范围和产出参数
/// </summary>
public partial class TbBuildingCard
{
    private readonly System.Collections.Generic.Dictionary<int, battle.BuildingCardConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.BuildingCardConfig> _dataList;
    
    public TbBuildingCard(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.BuildingCardConfig>(n);
        _dataList = new System.Collections.Generic.List<battle.BuildingCardConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.BuildingCardConfig _v;
            _v = global::GameConfig.battle.BuildingCardConfig.DeserializeBuildingCardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CardId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.BuildingCardConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.BuildingCardConfig> DataList => _dataList;

    public battle.BuildingCardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.BuildingCardConfig Get(int key) => _dataMap[key];
    public battle.BuildingCardConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

