
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 地图配置表：地图资源、人数范围、模式与局内对象约定
/// </summary>
public partial class TbMap
{
    private readonly System.Collections.Generic.Dictionary<int, battle.MapConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.MapConfig> _dataList;
    
    public TbMap(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.MapConfig>(n);
        _dataList = new System.Collections.Generic.List<battle.MapConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.MapConfig _v;
            _v = global::GameConfig.battle.MapConfig.DeserializeMapConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.MapId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.MapConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.MapConfig> DataList => _dataList;

    public battle.MapConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.MapConfig Get(int key) => _dataMap[key];
    public battle.MapConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

