
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.task
{
public sealed partial class TaskConfig : Luban.BeanBase
{
    public TaskConfig(ByteBuf _buf) 
    {
        TaskId = _buf.ReadInt();
        TaskType = _buf.ReadString();
        FeatureId = _buf.ReadString();
        ActivityId = _buf.ReadString();
        Title = _buf.ReadString();
        Description = _buf.ReadString();
        ProgressKey = _buf.ReadString();
        Target = _buf.ReadLong();
        RefreshGroup = _buf.ReadString();
        RewardCurrencyId = _buf.ReadInt();
        RewardCurrencyAmount = _buf.ReadLong();
        RewardItemId = _buf.ReadInt();
        RewardItemCount = _buf.ReadInt();
        Comment = _buf.ReadString();
    }

    public static TaskConfig DeserializeTaskConfig(ByteBuf _buf)
    {
        return new task.TaskConfig(_buf);
    }

    /// <summary>
    /// 任务ID
    /// </summary>
    public readonly int TaskId;
    /// <summary>
    /// 任务类型：Daily/Weekly/Achievement/Activity
    /// </summary>
    public readonly string TaskType;
    /// <summary>
    /// 关联 open_feature.featureId
    /// </summary>
    public readonly string FeatureId;
    /// <summary>
    /// 活动ID，仅用于归类筛选
    /// </summary>
    public readonly string ActivityId;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 进度Key，由服务端行为打点
    /// </summary>
    public readonly string ProgressKey;
    /// <summary>
    /// 目标值
    /// </summary>
    public readonly long Target;
    /// <summary>
    /// 刷新组
    /// </summary>
    public readonly string RefreshGroup;
    /// <summary>
    /// 奖励货币ID，0表示无
    /// </summary>
    public readonly int RewardCurrencyId;
    /// <summary>
    /// 奖励货币数量
    /// </summary>
    public readonly long RewardCurrencyAmount;
    /// <summary>
    /// 奖励道具ID，0表示无
    /// </summary>
    public readonly int RewardItemId;
    /// <summary>
    /// 奖励道具数量
    /// </summary>
    public readonly int RewardItemCount;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = -21545648;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "taskId:" + TaskId + ","
        + "taskType:" + TaskType + ","
        + "featureId:" + FeatureId + ","
        + "activityId:" + ActivityId + ","
        + "title:" + Title + ","
        + "description:" + Description + ","
        + "progressKey:" + ProgressKey + ","
        + "target:" + Target + ","
        + "refreshGroup:" + RefreshGroup + ","
        + "rewardCurrencyId:" + RewardCurrencyId + ","
        + "rewardCurrencyAmount:" + RewardCurrencyAmount + ","
        + "rewardItemId:" + RewardItemId + ","
        + "rewardItemCount:" + RewardItemCount + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

