
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.shop
{
/// <summary>
/// 局外商店表：常驻、活动和限时商店
/// </summary>
public partial class TbShop
{
    private readonly System.Collections.Generic.Dictionary<int, shop.ShopConfig> _dataMap;
    private readonly System.Collections.Generic.List<shop.ShopConfig> _dataList;
    
    public TbShop(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, shop.ShopConfig>(n);
        _dataList = new System.Collections.Generic.List<shop.ShopConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            shop.ShopConfig _v;
            _v = global::GameConfig.shop.ShopConfig.DeserializeShopConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ShopId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, shop.ShopConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<shop.ShopConfig> DataList => _dataList;

    public shop.ShopConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public shop.ShopConfig Get(int key) => _dataMap[key];
    public shop.ShopConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

