<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Hotfix</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entity\Entity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Client.Unity\Assets\GameScripts\HotFix\GameProto\LubanLib\*.cs" Link="Config\LubanLib\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
