
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.task
{
/// <summary>
/// 局外任务表：每日、周常、成就和活动任务
/// </summary>
public partial class TbTask
{
    private readonly System.Collections.Generic.Dictionary<int, task.TaskConfig> _dataMap;
    private readonly System.Collections.Generic.List<task.TaskConfig> _dataList;
    
    public TbTask(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, task.TaskConfig>(n);
        _dataList = new System.Collections.Generic.List<task.TaskConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            task.TaskConfig _v;
            _v = global::GameConfig.task.TaskConfig.DeserializeTaskConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.TaskId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, task.TaskConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<task.TaskConfig> DataList => _dataList;

    public task.TaskConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public task.TaskConfig Get(int key) => _dataMap[key];
    public task.TaskConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

